title: Python - это просто
description: Решение практических задач пошагового руководства по программированию и анализу данных
logo: /site/assets/img/logo.jpg
theme: jekyll-theme-minimal
show_downloads: true
google_analytics:
